name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose browser for manual run (chromium, firefox, webkit)'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        if [ -z "${{ github.event.inputs.browser }}" ]; then
          # Run tests on all browsers defined in matrix if no manual input given
          npx playwright test --project=${{ matrix.browser }}
        else
          # Run tests only on the browser specified as input during manual dispatch
          npx playwright test --project=${{ github.event.inputs.browser }}
        fi
      shell: bash
